proc help_command*() = 
  echo "用法: path-tool 选项 参数1 参数2..."
  echo ""
  echo "命令："
  echo "init 初始化并创建配置文件夹"
  echo "mode 显示当前的工作模式"
  echo "mode alternatives 切换为软链接工作原理"
  echo "mode path 切换为环境变量替换工作原理"
  echo "install <名称> <绝对路径> 注册命令到一个命令组(数组) 一对多的概念"
  echo "config 名称      列出<名称>的可选项，让用户自行配置命令对应的绝对路径"
  echo "remove <名称> <路径> 从名称替换组中删除<路径>"
  echo "remove_all <名称> 删除注册的命令（替换组）"
  echo "list <名称> 列出<名称>替换组中所有的可用候选项"
  echo ""

  echo "<名称> 是指命令组的名字(如gcc)"
  echo "<路径> 是指绝对路径，以windows路径格式"
  echo "在软链接模式下，路径会被软链接到etc/alternatives"
  echo "在path模式下，路径会被添加到etc/path/<名称>.json里的组中"

  echo ""
  echo "选项："
  echo "version 显示此程序版本信息"
  echo "help 显示帮助信息"
  echo ""

  echo "注意事项："
  echo r"使用软链接工作原理时，请使用形如path-tool install hello D:\hello\hello.exe 的方式添加命令"
  echo r"使用path工作原理是，请使用形如path-tool install hello D:\hello 的方式添加目录到环境变量"